---
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - 127.0.0.1:9000:8080

  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - keycloak:/opt/keycloak/data
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev

volumes:
  db:
  keycloak:
