"""init

Revision ID: 2d7953e8a560
Revises: 
Create Date: 2025-02-08 22:12:00.709555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d7953e8a560'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflowpattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patternnode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_pattern_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dataform_pydantic_str', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_pattern_id'], ['workflowpattern.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflowinstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_pattern_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_pattern_id'], ['workflowpattern.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instanceelement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_instance_id', sa.Integer(), nullable=True),
    sa.Column('pattern_node_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataform', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_node_id'], ['patternnode.id'], ),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflowinstance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patternedge',
    sa.Column('prev_id', sa.Integer(), nullable=False),
    sa.Column('next_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['next_id'], ['patternnode.id'], ),
    sa.ForeignKeyConstraint(['prev_id'], ['patternnode.id'], ),
    sa.PrimaryKeyConstraint('prev_id', 'next_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patternedge')
    op.drop_table('instanceelement')
    op.drop_table('workflowinstance')
    op.drop_table('patternnode')
    op.drop_table('workflowpattern')
    # ### end Alembic commands ###
