"""init

Revision ID: 3ce3f2e4a4bd
Revises: 
Create Date: 2025-02-27 00:03:47.653646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ce3f2e4a4bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elementedge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elementedge', schema=None) as batch_op:
        batch_op.drop_column('trigger')

    # ### end Alembic commands ###
