"""init

Revision ID: 98dad1025153
Revises: 
Create Date: 2025-02-17 20:54:14.425260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98dad1025153'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataform', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elementedge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prev_id', sa.Integer(), nullable=False),
    sa.Column('next_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['next_id'], ['element.id'], ),
    sa.ForeignKeyConstraint(['prev_id'], ['element.id'], ),
    sa.PrimaryKeyConstraint('id', 'prev_id', 'next_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elementedge')
    op.drop_table('element')
    op.drop_table('instance')
    # ### end Alembic commands ###
