"""init

Revision ID: c05b76deb636
Revises: 
Create Date: 2025-02-08 23:18:43.055153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c05b76deb636'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patternedge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prev_id', sa.Integer(), nullable=False),
    sa.Column('next_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['next_id'], ['patternnode.id'], ),
    sa.ForeignKeyConstraint(['prev_id'], ['patternnode.id'], ),
    sa.PrimaryKeyConstraint('id', 'prev_id', 'next_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patternedge')
    # ### end Alembic commands ###
